// Generated by gencpp from file rosinrange_msg/RangePose.msg
// DO NOT EDIT!


#ifndef ROSINRANGE_MSG_MESSAGE_RANGEPOSE_H
#define ROSINRANGE_MSG_MESSAGE_RANGEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace rosinrange_msg
{
template <class ContainerAllocator>
struct RangePose_
{
  typedef RangePose_<ContainerAllocator> Type;

  RangePose_()
    : header()
    , source_id(0)
    , destination_id(0)
    , range(0.0)
    , position()  {
    }
  RangePose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source_id(0)
    , destination_id(0)
    , range(0.0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _source_id_type;
  _source_id_type source_id;

   typedef uint64_t _destination_id_type;
  _destination_id_type destination_id;

   typedef double _range_type;
  _range_type range;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::rosinrange_msg::RangePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosinrange_msg::RangePose_<ContainerAllocator> const> ConstPtr;

}; // struct RangePose_

typedef ::rosinrange_msg::RangePose_<std::allocator<void> > RangePose;

typedef boost::shared_ptr< ::rosinrange_msg::RangePose > RangePosePtr;
typedef boost::shared_ptr< ::rosinrange_msg::RangePose const> RangePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosinrange_msg::RangePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosinrange_msg::RangePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosinrange_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'rosinrange_msg': ['/home/biorobotics/catkin_ws/src/amcl3d/rosinrange_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosinrange_msg::RangePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosinrange_msg::RangePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosinrange_msg::RangePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosinrange_msg::RangePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosinrange_msg::RangePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosinrange_msg::RangePose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosinrange_msg::RangePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "964eee1229cb150d70ba06950f025576";
  }

  static const char* value(const ::rosinrange_msg::RangePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x964eee1229cb150dULL;
  static const uint64_t static_value2 = 0x70ba06950f025576ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosinrange_msg::RangePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosinrange_msg/RangePose";
  }

  static const char* value(const ::rosinrange_msg::RangePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosinrange_msg::RangePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint64 source_id\n\
uint64 destination_id\n\
float64 range\n\
geometry_msgs/Point position\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::rosinrange_msg::RangePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosinrange_msg::RangePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source_id);
      stream.next(m.destination_id);
      stream.next(m.range);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RangePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosinrange_msg::RangePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosinrange_msg::RangePose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.source_id);
    s << indent << "destination_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.destination_id);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSINRANGE_MSG_MESSAGE_RANGEPOSE_H
